# amnesia_plugin - 配置文件
# 让麦麦选择性失忆,忘记之前的对话~ 支持忘记全部/最近/指定时间前的记忆,新增完全失忆模式 (改进自上下文清除插件)
# 配置版本: 1.3.0

[plugin]

# 是否启用麦麦失忆插件
enabled = true

# 配置文件版本
config_version = "1.3.0"

# 有权限让麦麦失忆的用户ID列表（管理员）
permission = ["1334431750"]


